version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_DATABASE: myapp_development
      TZ: Asia/Tokyo
    # https://sunday-morning.app/posts/2020-07-29-docker-mysql8-mbind-operation-not-permitted
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
    #    volumes:
    #      # 初期データを投入するSQLが格納されているdir
    #      - ./db/mysql_init:/docker-entrypoint-initdb.d
    #      # 永続化するときにマウントするdir
    #      - ./db/mysql_data:/var/lib/mysql
    #      - ./db/mysql_init/mysql-confd:/etc/mysql/conf.d

    #MySQL8.0からセキュリティが強化されたようで、--default-authentication-plugin=mysql_native_password を実行して認証方式を mysql_native_password へ変更する必要があり
    command: --default-authentication-plugin=mysql_native_password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 80 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - /myapp/node_modules
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - chrome
    environment:
      RAILS_DB_HOST: db # データベースコンテナ名と一致させる
      RAILS_DB_NAME: myapp_development # MYSQL_DATABASEと一致させる
      RAILS_DB_USER: root # MYSQL_USERと一致させる
      RAILS_DB_PASSWORD: password # MYSQL_PASSWORDと一致させる
      RAILS_ENV: development
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444